# This is a basic workflow to help you get started with Actions

name: Backend-Demo Docker Image CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    # pull_request:
    # branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Login to Azure Container Registry
        # https://docs.docker.com/engine/reference/commandline/login/#provide-a-password-using-stdin
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.LOGIN_SERVER_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
      - name: Installing az-cli getting packages requirements
        run: sudo apt-get update && sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
      - name: Download and install the Microsoft signing key
        run: curl -sL https://packages.microsoft.com/keys/microsoft.asc |
          gpg --dearmor |
          sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
      - name: Adding Azure CLI software repository
        run: AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
          sudo tee /etc/apt/sources.list.d/azure-cli.list
      - name: Updating repo and installing az-cli
        run: sudo apt-get update && sudo apt-get install azure-cli
      - name: Authenticating to Azure ACR
        run: az acr login -n ${{ secrets.LOGIN_SERVER_URL }}
      - name: Build the tagged Docker image
        run: docker build . --file backend/Dockerfile --tag backend-demo/spring-boot:v1.0
      - name: Push the tagged Docker image
        run: docker push backend-demo/spring-boot:v1.0
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag backend-demo/spring-boot:latest
      - name: Push the latest Docker image
        run: docker push backend-demo/spring-boot:latest
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
